version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  verify:
    docker:
      - image: cimg/node:22.16.0

    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Test Suite
          command: npm run test:ci

workflows:
  build_and_test:
    jobs:
      - verify
