version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  lint:
    docker:
      - image: cimg/node:22.16.0
    steps:
      - attach_workspace:
            at: .
      - run:
          name: Run ESLint
          command: npm run lint:ci

  setup:
    docker:
      - image: cimg/node:22.16.0
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  tests:
    docker:
      - image: cimg/node:22.16.0
    steps:
      - attach_workspace:
            at: .
      - run:
          name: Run Test Suite
          command: npm run test:ci

  tsc:
    docker:
      - image: cimg/node:22.16.0
    steps:
      - attach_workspace:
            at: .
      - run:
          name: Run TypeScript Compiler
          command: npm run tsc

workflows:
  build_and_test:
    jobs:
      - setup
      - lint:
          requires:
              - setup
      - tests:
          requires:
              - setup
      - tsc:
          requires:
              - setup
